/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0a839e96-2900-41b5-be5f-3ce483bcda34",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MrItormCZ",
    "aws_user_pools_web_client_id": "6kb1djdko5ckjijtjc76g1vl28",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "vehicleChecksSubmissionsAPI",
            "endpoint": "https://72uz49ufz2.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
